import sqlite3

conn = sqlite3.connect('Mail_Feature.db')
cursor = conn.cursor()
# cursor.execute('USE MAIL_FEATURE')
cursor.execute('''CREATE TABLE IF NOT EXISTS LEVEL1 (
    TYPE_OF_QUERY VARCHAR(40),
    REQUIRED_PARAMETER1 VARCHAR(40),
    REQUIRED_PARAMETER2 VARCHAR(40),
    REQUIRED_PARAMETER3 VARCHAR(40),
    DESTINATION_MAIL1 VARCHAR(40),
    DESTINATION_MAIL2 VARCHAR(40)
    
)''')
cursor.execute("INSERT INTO LEVEL1 VALUES('MEDICAL_LEAVE.txt', 'NAME', 'ROLL', 'NONE', 'FACULTY', 'NITHUPD@GMAIL.COM')")
cursor.execute("INSERT INTO LEVEL1 VALUES('ATTENDANCE_PERCENTAGE', 'NAME', 'ROLL', 'NONE', 'FACULTY', "
               "'ACADEMICS@IIITKOTTAYAM.AC.IN')")
cursor.execute('''INSERT INTO LEVEL1
        VALUES('FEE RECEIPT', 'NAME', 'ROLL', 'NONE', 'JSACADEMICS@IIITKOTTAYAM.AC.IN', 'ACCOUNTS@IIITKOTTAYAM.AC.IN')''')
cursor.execute('''INSERT INTO LEVEL1
        VALUES('EMERGENCY_OUTPASS', 'NAME', 'ROLL', 'NONE', 'WARDEN@IIITKOTTAYAM.AC.IN', 'ASO@IIITKOTTAYAM.AC.IN')''')


cursor.execute('SELECT * FROM LEVEL1')
conn.commit()
a = cursor.fetchall()
print(a)